services:
  verifylab:
    container_name: verifylab
    working_dir: /app
    env_file:
      - env.example
    build:
      context: .
      dockerfile: "./dev.Dockerfile"
    tty: true
    cpu_count: 1
    ports:
      - 9235:9235
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - jaeger
      - vault
    networks:
      - verifylab

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./ops/db/migrations/:/db/
    networks:
      - verifylab

  vault:
    image: hashicorp/vault
    ports:
      - "8300:8300"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
    networks:
      - verifylab

  jaeger:
    image: jaegertracing/jaeger:2.3.0
    environment:
      COLLECTOR_OTLP_ENABLED: true
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    networks:
      - verifylab

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - verifylab

networks:
  verifylab:
    driver: bridge
