// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID         uuid.UUID
	FirstName  string
	LastName   string
	MiddleName sql.NullString
	Email      sql.NullString
	Country    string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
