-- name: InsertCustomerIdentification :exec
INSERT INTO customer_identifications (
    id,
    first_name,
    last_name,
    middle_name,
    other_names,
    customer_id,
    pin,
    identification_type,
    issued_country,
    issued_date,
    place_of_birth,
    place_of_issue,
    date_of_birth,
    address_1,
    address_2,
    city,
    state_region,
    zip_code,
    created_at,
    updated_at
) VALUES (
@id,
@first_name,
@last_name,
@middle_name,
@other_names,
@customer_id,
@pin,
@identification_type,
@issued_country,
@issued_date,
@place_of_birth,
@place_of_issue,
@date_of_birth,
@address_1,
@address_2,
@city,
@state_region,
@zip_code,
@created_at,
@updated_at);


-- name: BulkInsertCustomerIdentifications :copyfrom
INSERT INTO customer_identifications (
    id,
    first_name,
    last_name,
    middle_name,
    other_names,
    customer_id,
    pin,
    identification_type,
    issued_country,
    issued_date,
    place_of_birth,
    place_of_issue,
    date_of_birth,
    address_1,
    address_2,
    city,
    state_region,
    zip_code,
    created_at,
    updated_at
) VALUES (
@id,
@first_name,
@last_name,
@middle_name,
@other_names,
@customer_id,
@pin,
@identification_type,
@issued_country,
@issued_date,
@place_of_birth,
@place_of_issue,
@date_of_birth,
@address_1,
@address_2,
@city,
@state_region,
@zip_code,
@created_at,
@updated_at);


-- name: QueryIdentificationsByCustomerID :many
SELECT id, customer_id, first_name, last_name, middle_name, other_names, pin, identification_type, issued_country, date_of_birth, issued_date,
created_at, updated_at
FROM customer_identifications WHERE customer_id = @customer_id;
