-- name: InsertIdentification :exec
INSERT INTO identifications (
    id,
    first_name,
    last_name,
    middle_name,
    other_names,
    pin,
    identification_type,
    issued_country,
    place_of_birth,
    place_of_issue,
    date_of_birth,
    address_1,
    address_2,
    city,
    state_region,
    zip_code,
    created_at,
    updated_at
) VALUES (
@id,
@first_name,
@last_name,
@middle_name,
@other_names,
@pin,
@identification_type,
@issued_country,
@place_of_birth,
@place_of_issue,
@date_of_birth,
@address_1,
@address_2,
@city,
@state_region,
@zip_code,
@created_at,
@updated_at);


-- name: BulkInsertIdentifications :copyfrom
INSERT INTO identifications (
    id,
    first_name,
    last_name,
    middle_name,
    other_names,
    pin,
    identification_type,
    issued_country,
    place_of_birth,
    place_of_issue,
    date_of_birth,
    address_1,
    address_2,
    city,
    state_region,
    zip_code,
    created_at,
    updated_at
) VALUES (
@id,
@first_name,
@last_name,
@middle_name,
@other_names,
@pin,
@identification_type,
@issued_country,
@place_of_birth,
@place_of_issue,
@date_of_birth,
@address_1,
@address_2,
@city,
@state_region,
@zip_code,
@created_at,
@updated_at);
