services:
    sight_cli:
        container_name: sight_cli
        working_dir: /app
        env_file:
            - env.example
        build:
            context: .
            dockerfile: "./cli.Dockerfile"
        tty: true
        cpu_count: 1
        ports:
            - 9235:9235
        volumes:
            - ./:/app/
        depends_on:
            - postgres
            - jaeger
            - vault
        networks:
            - sight

    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_HOST: "postgres"
            POSTGRES_DB: ${DATABASE_NAME}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        volumes:
            - ./ops/db/migrations/:/db/
        networks:
            - sight

    vault:
        image: hashicorp/vault
        ports:
            - "8300:8300"
        cap_add:
            - IPC_LOCK
        environment:
            VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8300"
            VAULT_DEV_ROOT_TOKEN_ID: "myroot"
        networks:
            - sight

    jaeger:
        image: jaegertracing/jaeger:2.3.0
        environment:
            COLLECTOR_OTLP_ENABLED: true
            COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
        ports:
            - "16686:16686"
            - "14268:14268"
            - "4317:4317"
            - "4318:4318"
            - "9411:9411"
        networks:
            - sight

    index:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
        expose:
            - "9200"
        ports:
            - 9200:9200
        container_name: index
        environment:
            - node.name=index
            - cluster.name=opensanctions-index
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - index-os-data:/usr/share/elasticsearch/data
        deploy:
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure

    app:
        image: ghcr.io/opensanctions/yente:4.4.0
        depends_on:
            - index
        ports:
            - 8000:8000
        environment:
            YENTE_INDEX_TYPE: "elasticsearch"
            YENTE_INDEX_URL: http://index:9200
            # Set this to a randomly generated string to enable the /updatez API:
            YENTE_UPDATE_TOKEN: ""
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 3s
        deploy:
            mode: replicated
            # Run multiple instances for better scale:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        networks:
            - sight

networks:
    sight:
        driver: bridge

volumes:
    index-os-data: null
